name: example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_rating:
    path: ../
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: "^3.3.0"
